In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/cleaned/os_market_2013_2025.csv")

df.head()

         Date  Android    iOS
0  2013-01-01    36.87  25.85
1  2013-02-01    36.90  27.21
2  2013-03-01    37.23  27.14
3  2013-04-01    38.34  26.46
4  2013-05-01    38.27  25.86

In [3]:
df.tail()

           Date  Android    iOS
151  2025-08-01    73.93  25.68
152  2025-09-01    75.17  24.45
153  2025-10-01    72.59  27.00
154  2025-11-01    71.90  27.67
155  2025-12-01    71.71  27.91

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     156 non-null    object
 1   Android  156 non-null    float64
 2   iOS      156 non-null    float64
dtypes: float64(2), object(1)
memory usage: 3.8+ KB

In [5]:
df["Android"] = df["Android"] / 100
df["iOS"] = df["iOS"] / 100

In [6]:
df.head()

         Date  Android     iOS
0  2013-01-01   0.3687  0.2585
1  2013-02-01   0.3690  0.2721
2  2013-03-01   0.3723  0.2714
3  2013-04-01   0.3834  0.2646
4  2013-05-01   0.3827  0.2586

In [7]:
df = df.dropna().reset_index(drop=True)

In [8]:
df = df.rename(columns={
    "Android": "x",
    "iOS": "y"
})

In [9]:
df.head()

         Date       x       y
0  2013-01-01  0.3687  0.2585
1  2013-02-01  0.3690  0.2721
2  2013-03-01  0.3723  0.2714
3  2013-04-01  0.3834  0.2646
4  2013-05-01  0.3827  0.2586

In [10]:
df.to_csv("../data/cleaned/os_model_data.csv", index=False)